// Code generated by "stringer -type=Op"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PushConst-0]
	_ = x[PushVar-1]
	_ = x[PopVar-2]
	_ = x[Plus-3]
	_ = x[Sub-4]
	_ = x[Mult-5]
	_ = x[Div-6]
	_ = x[Mod-7]
	_ = x[Gt-8]
	_ = x[Gte-9]
	_ = x[Lt-10]
	_ = x[Lte-11]
	_ = x[Eq-12]
	_ = x[Neq-13]
	_ = x[IfFalse-14]
	_ = x[Jump-15]
}

const _Op_name = "PushConstPushVarPopVarPlusSubMultDivModGtGteLtLteEqNeqIfFalseJump"

var _Op_index = [...]uint8{0, 9, 16, 22, 26, 29, 33, 36, 39, 41, 44, 46, 49, 51, 54, 61, 65}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
