// Code generated by "stringer -type=Op"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PushConst-0]
	_ = x[PushVar-1]
	_ = x[PopVar-2]
	_ = x[PlusInt-3]
	_ = x[MinusInt-4]
	_ = x[MultInt-5]
	_ = x[DivInt-6]
	_ = x[ModInt-7]
	_ = x[IfFalse-8]
	_ = x[Jump-9]
	_ = x[GtInt-10]
	_ = x[GteInt-11]
	_ = x[LtInt-12]
	_ = x[LteInt-13]
	_ = x[EqInt-14]
	_ = x[NeqInt-15]
}

const _Op_name = "PushConstPushVarPopVarPlusIntMinusIntMultIntDivIntModIntIfFalseJumpGtIntGteIntLtIntLteIntEqIntNeqInt"

var _Op_index = [...]uint8{0, 9, 16, 22, 29, 37, 44, 50, 56, 63, 67, 72, 78, 83, 89, 94, 100}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
