// Code generated by "stringer -type=Op"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PushConst-0]
	_ = x[PushVar-1]
	_ = x[PopVar-2]
	_ = x[Plus-3]
	_ = x[Plus_i16_p_c-4]
	_ = x[Sub-5]
	_ = x[Mult-6]
	_ = x[Div-7]
	_ = x[Mod-8]
	_ = x[Gt-9]
	_ = x[Gte-10]
	_ = x[Lt-11]
	_ = x[Lte-12]
	_ = x[Eq-13]
	_ = x[Neq-14]
	_ = x[IfFalse-15]
	_ = x[Jump-16]
}

const _Op_name = "PushConstPushVarPopVarPlusPlus_i16_p_cSubMultDivModGtGteLtLteEqNeqIfFalseJump"

var _Op_index = [...]uint8{0, 9, 16, 22, 26, 38, 41, 45, 48, 51, 53, 56, 58, 61, 63, 66, 73, 77}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
