// Code generated by "stringer -type=Type"; DO NOT EDIT.

package variant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ANY-0]
	_ = x[BOOL-1]
	_ = x[SINT-2]
	_ = x[INT-3]
	_ = x[DINT-4]
	_ = x[LINT-5]
	_ = x[USINT-6]
	_ = x[UINT-7]
	_ = x[UDINT-8]
	_ = x[ULINT-9]
	_ = x[REAL-10]
	_ = x[LREAL-11]
	_ = x[TIME-12]
	_ = x[TOD-13]
	_ = x[DT-14]
	_ = x[STRING-15]
	_ = x[CHAR-16]
	_ = x[WCHAR-17]
	_ = x[BYTE-18]
	_ = x[WORD-19]
	_ = x[DWORD-20]
	_ = x[LWORD-21]
}

const _Type_name = "ANYBOOLSINTINTDINTLINTUSINTUINTUDINTULINTREALLREALTIMETODDTSTRINGCHARWCHARBYTEWORDDWORDLWORD"

var _Type_index = [...]uint8{0, 3, 7, 11, 14, 18, 22, 27, 31, 36, 41, 45, 50, 54, 57, 59, 65, 69, 74, 78, 82, 87, 92}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
